server:
  port: 8080
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/
    password: jamespeter16
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
